config/routes.rb
Whereiring::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  match "/mu-f6c8d644-58973946-dd23236c-8f93a187", :to => proc {|env| [200, {"Content-Type" => "text/plain"}, ["42"]] }

  resources :axp12students do
    collection do
      get 'sendsms'
      post 'sentsms'
    end
  end
  
  match 'axp12sms' => redirect('/axp12students/sendsms')

  resources :momsgs

  root :to => 'axp12students#sendsms'

end

app/models/momsg.rb
class Momsg < ActiveRecord::Base
end

app/controllers/momsgs_controller.rb
class MomsgsController < ApplicationController
  # GET /momsgs
  # GET /momsgs.json
  before_filter :authenticate

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "" && password == ""
    end
  end

  def index
    @momsgs = Momsg.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @momsgs }
    end
  end

  # GET /momsgs/1
  # GET /momsgs/1.json
  def show
    @momsg = Momsg.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @momsg }
    end
  end

  # GET /momsgs/new
  # GET /momsgs/new.json
  def new
    @momsg = Momsg.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @momsg }
    end
  end

  # GET /momsgs/1/edit
  def edit
    @momsg = Momsg.find(params[:id])
  end

  # POST /momsgs
  # POST /momsgs.json
  def create
    #ClickATell posts this
    #Parameters:
    #"api_id"=>"3306957"
    #"from"=>"886975395038"
    #"to"=>"41798070085"
    #"timestamp"=>"2011-09-19 13:02:52"
    #"text"=>"Test of SMS 2"
    #"charset"=>"ISO-8859-1"
    #"udh"=>""
    #"moMsgId"=>"3e644dd7c1df98671fe41d26dfd73672"

    @momsg = Momsg.new(:from => params[:from], :text => params[:text])
    
    @momsg.save

    respond_to do |format|
        format.html { redirect_to @momsg }
    end
  end

  # PUT /momsgs/1
  # PUT /momsgs/1.json
  def update
    @momsg = Momsg.find(params[:id])

    respond_to do |format|
      if @momsg.update_attributes(params[:momsg])
        format.html { redirect_to @momsg, notice: 'Momsg was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @momsg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /momsgs/1
  # DELETE /momsgs/1.json
  def destroy
    @momsg = Momsg.find(params[:id])
    @momsg.destroy

    respond_to do |format|
      format.html { redirect_to momsgs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/momsgs_helper.rb
module MomsgsHelper
end

app/views/momsgs/_form.html.erb
<%= form_for(@momsg) do |f| %>
  <% if @momsg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@momsg.errors.count, "error") %> prohibited this momsg from being saved:</h2>

      <ul>
      <% @momsg.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br />
    <%= f.number_field :from %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/momsgs/edit.html.erb
<h1>Editing momsg</h1>

<%= render 'form' %>

<%= link_to 'Show', @momsg %> |
<%= link_to 'Back', momsgs_path %>

app/views/momsgs/new.html.erb
<h1>New momsg</h1>

<%= render 'form' %>

<%= link_to 'Back', momsgs_path %>

app/views/momsgs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From:</b>
  <%= @momsg.from %>
</p>

<p>
  <b>Message:</b>
  <%= @momsg.text %>
</p>


<%= link_to 'Edit', edit_momsg_path(@momsg) %> |
<%= link_to 'Back', momsgs_path %>